name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0" # خليه مناسب لإصدار Flutter اللي عندك

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.19.0
  

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - android/assets/fonts/Poppins-Regular.ttf
  fonts:
    - family: Poppins
      fonts:
        - asset: android/assets/fonts/Poppins-Regular.ttf
